### ISSUE TITLE
NeurIPS Competitions Blog Post links to wrong page

### ISSUE THREAD

**Issue by hcarlens** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#10]
Hi!

I just wanted to point out that the [NeurIPS Competitions blog post](https://blog.neurips.cc/2023/06/14/announcing-the-neurips-2023-competitions/) still links to https://weiweiy.github.io/, which forwards to https://kaleab-k.github.io/LLMEC/index instead of https://llm-efficiency-challenge.github.io/.

Best,
Harald

**Comment by weiweiy** [comment]
@hcarlens, thank you for letting us know. We contacted NeurIPS competition chairs to correct it. Cheers!

**Comment by msaroufim** [comment]
This was fixed
