### ISSUE TITLE
Test HELM locally on gsm8k Request error 

### ISSUE THREAD

**Issue by MrJungle1** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#14]
I deployed HELM according to helm.md. When I use the following conf it is normal 
```entries: [{description: "mmlu:model=neurips/local,subject=college_computer_science", priority: 4}] ```
But when I use 
```entries: [{description: "gsm:model=neurips/local", priority: 4}]```
there will be the following prompt
![](https://user-images.githubusercontent.com/43968255/261482328-016e29e9-0b6b-47a1-a63a-b294b95d3fd6.png)

**Comment by msaroufim** [comment]
This should get fixed by https://github.com/stanford-crfm/helm/pull/1807#event-10161085934
