### ISSUE TITLE
Unable to install helm

### ISSUE THREAD

**Issue by pskadasi** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#15]
Hi, I am not able to run the below command:

`pip install git+https://github.com/drisspg/helm.git@neruips_client`

below is the snapshot of error:

<img width="1435" alt="image" src="https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge/assets/48944276/c547cf06-fb1f-4ee5-bf6c-d92ec8ac9868">

any workaround for this?

**Comment by aniketmaurya** [comment]
did you create a new virtual environment?

**Comment by pskadasi** [comment]
yes, i did. can you pls walk through the process of set up. starting from setting up docker.

**Comment by msaroufim** [comment]
We need to update those docs, since this client was now upstreamed to HELM https://github.com/stanford-crfm/helm/pull/1693

cc @drisspg

**Comment by msaroufim** [comment]
I'd just try out an older numpy version that was printed in your console

**Comment by matthewdouglas** [comment]
@pskadasi What version of Python are you using? It looks to me like it might be 3.7, and you're going to want to use Python >= 3.8, which is required for helm. Besides that, [3.7 reached EOL](https://devguide.python.org/versions/) a couple months ago.

**Comment by msaroufim** [comment]
I'm gonna close this because @matthewdouglas is correct, HELM mentions 3.8 as the minimal python dependency on their docs
