### ISSUE TITLE
lit-gpt error with quantize lib

### ISSUE THREAD

**Issue by QuyAnh2005** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#27]
I got this error in [block code](https://github.com/Lightning-AI/lit-gpt/blob/966646a428546360a9857ac7814869cc72ff6edb/lit_gpt/utils.py#L68C9-L72C94)
```
from quantize.bnb import Linear4bit

class QuantizedLinear(Linear4bit):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, quant_type="nf4", compress_statistics=True, **kwargs)
```

![image](https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge/assets/80700452/ccf03786-e3d2-49be-a459-2991e38d0750)

but, how to fix?

**Comment by msaroufim** [comment]
Might be best to post this issue on the Lightning repo - cc @carmocca

**Comment by QuyAnh2005** [comment]
Yes, I created an issue at [here](https://github.com/Lightning-AI/lit-gpt/issues/574) @msaroufim @carmocca

**Comment by carmocca** [comment]
Sorry for the inconvenience @QuyAnh2005! I'll fix it in lit-gpt. You can close this issue
