### ISSUE TITLE
Remove multilingual tasks

### ISSUE THREAD

**Issue by jph00** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#37]
I wonder if you might consider getting rid of the `conlang_translation` task. Doing multilingual NLP is a whole different thing, and it's useful, but if everything else is English, then having one translation task seems like a distraction.

...And maybe `language_identification`. That's already so easy and effective with fasttext-style models anyway, that it seems like a low-priority thing for people to be working on with LLMs.

AFAICT removing these two would mean people can focus on English tasks. There's already a lot to do, so this would make life easier!
cc @weiweiy, @artidoro and @perlitz as requested by @msaroufim

**Comment by weiweiy** [comment]
I agree with @jph00 on removing colang and language_identification tasks. Will make a PR.

**Comment by weiweiy** [comment]
@msaroufim  https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge/pull/40
