### ISSUE TITLE
I have a question about "build_run_specs_full.py" file.

### ISSUE THREAD

**Issue by gyuwon12** [llm-efficiency-challenge/neurips_llm_efficiency_challenge#41]
https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge/blob/master/build_run_specs_full.py

Hello, I have a question in that file!

No other than that, there seem to be a total of 3 files that can proceed with the helm benchmark test, and I wonder if the final evaluation is done with that file, or with the file "run_specs_full_coase_600_budge.conf"!

Thank you.

**Comment by msaroufim** [comment]
It's going to be an iterative process depending on how many applications we get but first pass will be to run the 600 budget conf and we will keep increasing the budget until full to determine the final winner
